name: Build & Test Windows

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
jobs:
  build-test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.2.1'
        arch: 'win64_mingw81'
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.19.x'
    - name: Build RailwayBuilder
      run: |
            cmake -Bbuild -G "MinGW Makefiles"
            cmake --build build
    - name: Run Tests
      run: ./build/test/RailwayBuilderTests
