name: Build & Test

on: [push]
jobs:
  build-linux:
  runs-on: ubuntu-18.04
  steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.19.x'
    - name: Build RailwayBuilder  
        run:|
            mkdir build
            cd build
            cmake ..
