name: Build & Publish Docs

#Trigger on push or pull requests for master branch.
on:
  push:
    branches:
      - main
      - Add-Publish-Docs-CI
  pull_request:
    branches:
      - main

jobs:
  publish-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
    
      # Build the HTML documentation
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
            doxyfile-path: ./Doxyfile
            working-directory: .
        
      # Deploy the HTML documentation to GitHub Pages
      - name: GH Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs/html
            allow_empty_commit: false
            force_orphan: true
            publish_branch: gh-pages
